import Foundation
import CCore

public class MessageHeader {
    private var nativeInstance:CMessageHeader;
    
    internal func CMessageHeader() -> CMessageHeader {
        return nativeInstance;
    }
    
    internal init(_ header:CMessageHeader) {
        self.nativeInstance = header;
    }
    
    public init(data:Data) {
        self.nativeInstance = CMessageHeader_new();
        self.importHeadersData(data: data);
    }
    
    deinit {
        nativeInstance.release()
    }
    
    /** Message-ID field.*/
    public var messageID : String? {
        set { String.utf16(newValue, { self.nativeInstance.messageID = $0 }) }
        get { return String(utf16: self.nativeInstance.messageID); }
    }
    
    /** Message-ID auto-generated flag.*/
    public var isMessageIDAutoGenerated : Bool {
        get { return self.nativeInstance.isMessageIDAutoGenerated() }
    }
    
    /** References field. It's an array of message-ids.*/
    public var references : Array<String> {
        set { self.nativeInstance.references = Array<String>.cast(newValue) }
        get { return Array<String>.cast(self.nativeInstance.references) }
    }
    
    /** In-Reply-To field. It's an array of message-ids.*/
    public var inReplyTo : Array<String> {
        set { self.nativeInstance.inReplyTo = Array<String>.cast(newValue) }
        get { return Array<String>.cast(self.nativeInstance.inReplyTo) }
    }
    
    /** To field: recipient of the message. It's an array of MCOAddress.*/
    public var to: Array<Address> {
        set { self.nativeInstance.to = Array<Address>.cast(newValue) }
        get { return Array<Address>.cast(self.nativeInstance.to) }
    }
    
    /** Cc field: cc recipient of the message. It's an array of MCOAddress.*/
    public var cc: Array<Address> {
        set { self.nativeInstance.cc = Array<Address>.cast(newValue) }
        get { return Array<Address>.cast(self.nativeInstance.cc) }
    }
    
    /** Bcc field: bcc recipient of the message. It's an array of MCOAddress.*/
    public var bcc: Array<Address> {
        set { self.nativeInstance.bcc = Array<Address>.cast(newValue) }
        get { return Array<Address>.cast(self.nativeInstance.bcc) }
    }
    
    /** Reply-To field. It's an array of MCOAddress.*/
    public var replyTo: Array<Address> {
        set { self.nativeInstance.replyTo = Array<Address>.cast(newValue) }
        get { return Array<Address>.cast(self.nativeInstance.replyTo) }
    }
    
    /** Subject of the message.*/
    public var subject: String? {
        set { String.utf16(newValue, { self.nativeInstance.subject = $0 }) }
        get { return String(utf16: self.nativeInstance.subject) }
    }
    
    /** Email user agent name: X-Mailer header.*/
    public var userAgent: String? {
        set { String.utf16(newValue, { self.nativeInstance.userAgent = $0 }) }
        get { return String(utf16: self.nativeInstance.userAgent) }
    }
    
    /** Adds a custom header.*/
    public func setExtraHeaderValue(value: String, name: String) {
        String.utf16(value, name, { valuePtr, namePtr in
            nativeInstance.setExtraHeaderValue(value: valuePtr, name: namePtr)
        })
    }
    
    /** Remove a given custom header.*/
    public func removeExtraHeaderForName(name: String) {
        String.utf16(name, { nativeInstance.removeExtraHeaderForName(name: $0) })
    }
    
    /** Returns the value of a given custom header.*/
    public func extraHeaderValueForName(name: String) -> String? {
        return String(utf16: String.utf16(name, { nativeInstance.extraHeaderValueForName(name: $0)}))
    }
    
    /** Returns an array with the names of all custom headers.*/
    public func allExtraHeadersNames() -> Array<String> {
        return Array<String>.cast(nativeInstance.allExtraHeadersNames());
    }
    
    /** Extracted subject (also remove square brackets).*/
    public func extractedSubject() -> String? {
        return String(utf16: nativeInstance.extractedSubject());
    }
    
    /** Extracted subject (don't remove square brackets).*/
    public func partialExtractedSubject() -> String? {
        return String(utf16: nativeInstance.partialExtractedSubject());
    }
    
    /** Fill the header using the given RFC 822 data.*/
    public func importHeadersData(data: Data) {
        let bytes: UnsafePointer<Int8>? = data.withUnsafeBytes{(bytes: UnsafePointer<Int8>)-> UnsafePointer<Int8> in
            return bytes;
        }
        nativeInstance.importHeadersData(bytes: bytes, length: UInt32(data.count));
    }
    
    /** Returns a header that can be used as a base for a reply message.*/
    public func replyHeaderWithExcludedRecipients(excludedRecipients: Array<Address>) -> MessageHeader {
        return MessageHeader(nativeInstance.replyHeaderWithExcludedRecipients(excludedRecipients: Array<Address>.cast(excludedRecipients)));
    }
    
    /** Returns a header that can be used as a base for a reply all message.*/
    public func replyAllHeaderWithExcludedRecipients(excludedRecipients: Array<Address>) -> MessageHeader {
        return MessageHeader(nativeInstance.replyAllHeaderWithExcludedRecipients(excludedRecipients: Array<Address>.cast(excludedRecipients)));
    }
    
    /** Returns a header that can be used as a base for a forward message.*/
    public func forwardHeader() -> MessageHeader {
        return MessageHeader(nativeInstance.forwardHeader());
    }
    
}
