set(public_headers
MailCore.h
core/MCCore.h
core/abstract/MCAbstract.h
core/abstract/MCAbstractMessage.h
core/abstract/MCAbstractMessagePart.h
core/abstract/MCAbstractMultipart.h
core/abstract/MCAbstractPart.h
core/abstract/MCAddress.h
core/abstract/MCMessageConstants.h
core/abstract/MCMessageHeader.h
core/basetypes/MCArray.h
core/basetypes/MCAssert.h
core/basetypes/MCAutoreleasePool.h
core/basetypes/MCBaseTypes.h
core/basetypes/MCConnectionLogger.h
core/basetypes/MCData.h
core/basetypes/MCDataDecoderUtils.h
core/basetypes/MCDataStreamDecoder.h
core/basetypes/MCHash.h
core/basetypes/MCHashMap.h
core/basetypes/MCHTMLCleaner.h
core/basetypes/MCICUTypes.h
core/basetypes/MCIndexSet.h
core/basetypes/MCIterator.h
core/basetypes/MCJSON.h
core/basetypes/MCLibetpanTypes.h
core/basetypes/MCLog.h
core/basetypes/MCMD5.h
core/basetypes/MCNull.h
core/basetypes/MCObject.h
core/basetypes/MCOperation.h
core/basetypes/MCOperationCallback.h
core/basetypes/MCOperationQueue.h
core/basetypes/MCRange.h
core/basetypes/MCSet.h
core/basetypes/MCString.h
core/basetypes/MCUtils.h
core/basetypes/MCValue.h
core/imap/MCIMAP.h
core/imap/MCIMAPFolder.h
core/imap/MCIMAPFolderStatus.h
core/imap/MCIMAPIdentity.h
core/imap/MCIMAPMessage.h
core/imap/MCIMAPMessagePart.h
core/imap/MCIMAPMultipart.h
core/imap/MCIMAPNamespace.h
core/imap/MCIMAPNamespaceItem.h
core/imap/MCIMAPPart.h
core/imap/MCIMAPProgressCallback.h
core/imap/MCIMAPSearchExpression.h
core/imap/MCIMAPSession.h
core/imap/MCIMAPSyncResult.h
core/nntp/MCNNTP.h
core/nntp/MCNNTPGroupInfo.h
core/nntp/MCNNTPProgressCallback.h
core/nntp/MCNNTPSession.h
core/pop/MCPOP.h
core/pop/MCPOPMessageInfo.h
core/pop/MCPOPProgressCallback.h
core/pop/MCPOPSession.h
core/provider/MCAccountValidator.h
core/provider/MCMailProvider.h
core/provider/MCMailProvidersManager.h
core/provider/MCMXRecordResolverOperation.h
core/provider/MCNetService.h
core/provider/MCProvider.h
core/renderer/MCAddressDisplay.h
core/renderer/MCDateFormatter.h
core/renderer/MCHTMLRendererCallback.h
core/renderer/MCRenderer.h
core/rfc822/MCAttachment.h
core/rfc822/MCMessageBuilder.h
core/rfc822/MCMessageParser.h
core/rfc822/MCMessagePart.h
core/rfc822/MCMultipart.h
core/rfc822/MCRFC822.h
core/smtp/MCSMTP.h
core/smtp/MCSMTPProgressCallback.h
core/smtp/MCSMTPSession.h
async/MCAsync.h
async/imap/MCAsyncIMAP.h
async/imap/MCIMAPAppendMessageOperation.h
async/imap/MCIMAPAsyncSession.h
async/imap/MCIMAPCapabilityOperation.h
async/imap/MCIMAPCheckAccountOperation.h
async/imap/MCIMAPCopyMessagesOperation.h
async/imap/MCIMAPCustomCommandOperation.h
async/imap/MCIMAPFetchContentOperation.h
async/imap/MCIMAPFetchContentToFileOperation.h
async/imap/MCIMAPFetchFoldersOperation.h
async/imap/MCIMAPFetchMessagesOperation.h
async/imap/MCIMAPFetchNamespaceOperation.h
async/imap/MCIMAPFetchParsedContentOperation.h
async/imap/MCIMAPFolderInfo.h
async/imap/MCIMAPFolderInfoOperation.h
async/imap/MCIMAPFolderStatusOperation.h
async/imap/MCIMAPIdentityOperation.h
async/imap/MCIMAPIdleOperation.h
async/imap/MCIMAPMessageRenderingOperation.h
async/imap/MCIMAPMoveMessagesOperation.h
async/imap/MCIMAPOperation.h
async/imap/MCIMAPOperationCallback.h
async/imap/MCIMAPQuotaOperation.h
async/imap/MCIMAPSearchOperation.h
async/nntp/MCAsyncNNTP.h
async/nntp/MCNNTPAsyncSession.h
async/nntp/MCNNTPFetchAllArticlesOperation.h
async/nntp/MCNNTPFetchArticleOperation.h
async/nntp/MCNNTPFetchHeaderOperation.h
async/nntp/MCNNTPFetchOverviewOperation.h
async/nntp/MCNNTPFetchServerTimeOperation.h
async/nntp/MCNNTPListNewsgroupsOperation.h
async/nntp/MCNNTPOperation.h
async/nntp/MCNNTPOperationCallback.h
async/nntp/MCNNTPPostOperation.h
async/pop/MCAsyncPOP.h
async/pop/MCPOPAsyncSession.h
async/pop/MCPOPFetchHeaderOperation.h
async/pop/MCPOPFetchMessageOperation.h
async/pop/MCPOPFetchMessagesOperation.h
async/pop/MCPOPOperation.h
async/pop/MCPOPOperationCallback.h
async/smtp/MCAsyncSMTP.h
async/smtp/MCSMTPAsyncSession.h
async/smtp/MCSMTPOperation.h
async/smtp/MCSMTPOperationCallback.h
)