#ifndef MAILCORE_CMESSAGE_HEADER_H
#define MAILCORE_CMESSAGE_HEADER_H

#include "stdint.h"
#include <time.h>

#include "CBase.h"
#include "CArray.h"
#include "CAddress.h"
#include "MailCoreString.h"

#ifdef __cplusplus

namespace mailcore {
    class MessageHeader;
}

extern "C" {
#endif
    
    C_SYNTHESIZE_STRUCT_DEFINITION(CMessageHeader, mailcore::MessageHeader)
    
	CMAILCORE_EXPORT C_SYNTHESIZE_COBJECT_CAST_DEFINITION(CMessageHeader)
    
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, MailCoreString, messageID, setMessageID)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CArray, references, setReferences)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CArray, inReplyTo, setInReplyTo)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CArray, to, setTo)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CArray, cc, setCc)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CArray, bcc, setBcc)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CArray, replyTo, setReplyTo)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, MailCoreString, subject, setSubject)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, MailCoreString, userAgent, setUserAgent)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, time_t, receivedDate, setReceivedDate)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, time_t, date, setDate)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CAddress, sender, setSender)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CAddress, from, setFrom)
	CMAILCORE_EXPORT C_SYNTHESIZE_PROPERTY_DEFINITION(CMessageHeader, CAddress, sender, setSender)
    
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, bool, isMessageIDAutoGenerated)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, void, setExtraHeader, MailCoreString, MailCoreString)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, void, removeExtraHeader, MailCoreString)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, MailCoreString, extraHeaderValueForName, MailCoreString)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, CArray, allExtraHeadersNames)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, MailCoreString, extractedSubject)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, MailCoreString, partialExtractedSubject)
    
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, void, importHeadersData, CData)
    
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, CMessageHeader, replyHeaderWithExcludedRecipients, CArray)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, CMessageHeader, replyAllHeaderWithExcludedRecipients, CArray)
	CMAILCORE_EXPORT C_SYNTHESIZE_FUNC_DEFINITION(CMessageHeader, CMessageHeader, forwardHeader)
    
	CMAILCORE_EXPORT C_SYNTHESIZE_STATIC_FUNC_DEFINITION(CMessageHeader, CMessageHeader, init)
    
#ifdef __cplusplus
}
#endif

#endif
