//
//  MailCore.h
//  mailcore2
//
//  Created by Anton Pogonets on 19.05.17.
//  Copyright © 2017 MailCore. All rights reserved.
//

#import <MailCore/MCAbstract.h>
#import <MailCore/MCAbstractMessage.h>
#import <MailCore/MCAbstractMessagePart.h>
#import <MailCore/MCAbstractMultipart.h>
#import <MailCore/MCAbstractPart.h>
#import <MailCore/MCAccountValidator.h>
#import <MailCore/MCAddress.h>
#import <MailCore/MCAddressDisplay.h>
#import <MailCore/MCArray.h>
#import <MailCore/MCAssert.h>
#import <MailCore/MCAsync.h>
#import <MailCore/MCAsyncIMAP.h>
#import <MailCore/MCAsyncNNTP.h>
#import <MailCore/MCAsyncPOP.h>
#import <MailCore/MCAsyncSMTP.h>
#import <MailCore/MCAttachment.h>
#import <MailCore/MCAutoreleasePool.h>
#import <MailCore/MCBaseTypes.h>
#import <MailCore/MCConnectionLogger.h>
#import <MailCore/MCCore.h>
#import <MailCore/MCData.h>
#import <MailCore/MCDateFormatter.h>
#import <MailCore/MCHTMLCleaner.h>
#import <MailCore/MCHTMLRendererCallback.h>
#import <MailCore/MCHash.h>
#import <MailCore/MCHashMap.h>
#import <MailCore/MCICUTypes.h>
#import <MailCore/MCIMAP.h>
#import <MailCore/MCIMAPAppendMessageOperation.h>
#import <MailCore/MCIMAPAsyncSession.h>
#import <MailCore/MCIMAPCapabilityOperation.h>
#import <MailCore/MCIMAPCheckAccountOperation.h>
#import <MailCore/MCIMAPConnectOperation.h>
#import <MailCore/MCIMAPCopyMessagesOperation.h>
#import <MailCore/MCIMAPCustomCommandOperation.h>
#import <MailCore/MCIMAPFetchContentOperation.h>
#import <MailCore/MCIMAPFetchContentToFileOperation.h>
#import <MailCore/MCIMAPFetchFoldersOperation.h>
#import <MailCore/MCIMAPFetchMessagesOperation.h>
#import <MailCore/MCIMAPFetchNamespaceOperation.h>
#import <MailCore/MCIMAPFetchParsedContentOperation.h>
#import <MailCore/MCIMAPFolder.h>
#import <MailCore/MCIMAPFolderInfo.h>
#import <MailCore/MCIMAPFolderInfoOperation.h>
#import <MailCore/MCIMAPFolderStatus.h>
#import <MailCore/MCIMAPFolderStatusOperation.h>
#import <MailCore/MCIMAPIdentity.h>
#import <MailCore/MCIMAPIdentityOperation.h>
#import <MailCore/MCIMAPIdleOperation.h>
#import <MailCore/MCIMAPMessage.h>
#import <MailCore/MCIMAPMessagePart.h>
#import <MailCore/MCIMAPMessageRenderingOperation.h>
#import <MailCore/MCIMAPMoveMessagesOperation.h>
#import <MailCore/MCIMAPMultipart.h>
#import <MailCore/MCIMAPNamespace.h>
#import <MailCore/MCIMAPNamespaceItem.h>
#import <MailCore/MCIMAPNoopOperation.h>
#import <MailCore/MCIMAPOperation.h>
#import <MailCore/MCIMAPOperationCallback.h>
#import <MailCore/MCIMAPPart.h>
#import <MailCore/MCIMAPProgressCallback.h>
#import <MailCore/MCIMAPQuotaOperation.h>
#import <MailCore/MCIMAPSearchExpression.h>
#import <MailCore/MCIMAPSearchOperation.h>
#import <MailCore/MCIMAPSession.h>
#import <MailCore/MCIMAPSyncResult.h>
#import <MailCore/MCIndexSet.h>
#import <MailCore/MCIterator.h>
#import <MailCore/MCJSON.h>
#import <MailCore/MCLibetpanTypes.h>
#import <MailCore/MCLog.h>
#import <MailCore/MCMD5.h>
#import <MailCore/MCMXRecordResolverOperation.h>
#import <MailCore/MCMailProvider.h>
#import <MailCore/MCMailProvidersManager.h>
#import <MailCore/MCMainThread.h>
#import <MailCore/MCMessageBuilder.h>
#import <MailCore/MCMessageConstants.h>
#import <MailCore/MCMessageHeader.h>
#import <MailCore/MCMessageParser.h>
#import <MailCore/MCMessagePart.h>
#import <MailCore/MCMultipart.h>
#import <MailCore/MCNNTP.h>
#import <MailCore/MCNNTPAsyncSession.h>
#import <MailCore/MCNNTPFetchAllArticlesOperation.h>
#import <MailCore/MCNNTPFetchArticleOperation.h>
#import <MailCore/MCNNTPFetchHeaderOperation.h>
#import <MailCore/MCNNTPFetchOverviewOperation.h>
#import <MailCore/MCNNTPFetchServerTimeOperation.h>
#import <MailCore/MCNNTPGroupInfo.h>
#import <MailCore/MCNNTPListNewsgroupsOperation.h>
#import <MailCore/MCNNTPOperation.h>
#import <MailCore/MCNNTPOperationCallback.h>
#import <MailCore/MCNNTPPostOperation.h>
#import <MailCore/MCNNTPProgressCallback.h>
#import <MailCore/MCNNTPSession.h>
#import <MailCore/MCNetService.h>
#import <MailCore/MCNull.h>
#import <MailCore/MCObject.h>
#import <MailCore/MCOperation.h>
#import <MailCore/MCOperationCallback.h>
#import <MailCore/MCOperationQueue.h>
#import <MailCore/MCPOP.h>
#import <MailCore/MCPOPAsyncSession.h>
#import <MailCore/MCPOPFetchHeaderOperation.h>
#import <MailCore/MCPOPFetchMessageOperation.h>
#import <MailCore/MCPOPFetchMessagesOperation.h>
#import <MailCore/MCPOPMessageInfo.h>
#import <MailCore/MCPOPNoopOperation.h>
#import <MailCore/MCPOPOperation.h>
#import <MailCore/MCPOPOperationCallback.h>
#import <MailCore/MCPOPProgressCallback.h>
#import <MailCore/MCPOPSession.h>
#import <MailCore/MCProvider.h>
#import <MailCore/MCRFC822.h>
#import <MailCore/MCRange.h>
#import <MailCore/MCRenderer.h>
#import <MailCore/MCSMTP.h>
#import <MailCore/MCSMTPAsyncSession.h>
#import <MailCore/MCSMTPNoopOperation.h>
#import <MailCore/MCSMTPOperation.h>
#import <MailCore/MCSMTPOperationCallback.h>
#import <MailCore/MCSMTPProgressCallback.h>
#import <MailCore/MCSMTPSession.h>
#import <MailCore/MCSet.h>
#import <MailCore/MCSizeFormatter.h>
#import <MailCore/MCString.h>
#import <MailCore/MCUtils.h>
#import <MailCore/MCValue.h>

#include <MailCore/CIndexSet.h>
#include <MailCore/CArray.h>
#include <MailCore/CObject.h>
#include <MailCore/CAbstractMessage.h>
#include <MailCore/CAbstractMessagePart.h>
#include <MailCore/CAbstractMultipart.h>
#include <MailCore/CAddress.h>
#include <MailCore/CAbstractPart.h>
#include <MailCore/CMessageHeader.h>
#include <MailCore/CAbstractMessageRendererCallback.h>
#include <MailCore/CIMAPAsyncSession.h>
#include <MailCore/COperation.h>
#include <MailCore/CIMAPBaseOperation.h>
#include <MailCore/CIMAPIdleOperation.h>
#include <MailCore/CIMAPFolder.h>
#include <MailCore/CIMAPMessage.h>
#include <MailCore/CIMAPMessagePart.h>
#include <MailCore/CIMAPMultipart.h>
#include <MailCore/CIMAPNamespace.h>
#include <MailCore/CIMAPNamespaceItem.h>
#include <MailCore/CIMAPPart.h>
#include <MailCore/CIMAPFolderInfo.h>
#include <MailCore/CIMAPFolderStatus.h>
#include <MailCore/CIMAPSearchExpression.h>
#include <MailCore/CSMTPSession.h>
#include <MailCore/CSMTPOperation.h>
#include <MailCore/CAttachment.h>
#include <MailCore/CMessageBuilder.h>
#include <MailCore/CMessageParser.h>
#include <MailCore/CIMAPFetchFoldersOperation.h>